version: '3.7'
services:
  postgres:
    image: postgres:14-alpine
    ports:
      - 5432:5432
    volumes:
      - ~/apps/postgres:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=123459
      - POSTGRES_USER=test
      - POSTGRES_DB=testdb
    networks:
      - app
  api:
    build: .
    env_file: ./.env
    ports:
      - "8080:8080"
    depends_on:
      - postgres
    networks:
      - app
  web:
    build:
      context: .
      dockerfile: view/Dockerfile
    ports:
      - "8000:80"
    depends_on:
      - api
    networks:
      - app

networks:
  app:
    driver: bridge