version: '3.7'
services:
  postgres:
    env_file: ./.env
    image: postgres:14-alpine
    ports:
      - "5432:5432"
    volumes:
      - ~/apps/postgres:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_DB=${POSTGRES_DB_NAME}
    networks:
      - app
  api:
    build: .
    env_file: ./.env
    ports:
      - "8080:8080"
    depends_on:
      - postgres
    networks:
      - app
  web:
    build:
      context: .
      dockerfile: view/Dockerfile
    ports:
      - "8000:80"
    depends_on:
      - api
    networks:
      - app

networks:
  app:
    driver: bridge