create table if not exists customer_companies
(
    company_id                                    int generated by default as identity primary key,
    company_name                                  varchar(255)
);

insert into customer_companies (company_id, company_name)
values (1, 'Roga & Kopyta'),
       (2, 'Pupkin & Co');