create table if not exists orders
(
    id          integer generated by default as identity constraint orders_pk primary key,
    created_at  timestamptz  not null,
    order_name  varchar(255) not null,
    customer_id varchar(255)
        constraint orders_customers_user_id_fk
            references customers
);

insert into orders (id, created_at, order_name, customer_id)
values
    (1,timestamp with time zone '2020-01-02 15:34:12 +11:00','PO #001-I','ivan'),
    (2,timestamp with time zone '2020-01-15 17:34:12 +11:00','PO #002-I','ivan'),
    (3,timestamp with time zone '2020-01-05 05:34:12 +11:00','PO #003-I','ivan'),
    (4,timestamp with time zone '2020-02-02 15:34:12 +11:00','PO #004-I','ivan'),
    (5,timestamp with time zone '2020-01-03 10:34:12 +11:00','PO #005-I','ivan'),
    (6,timestamp with time zone '2020-01-02 15:34:12 +11:00','PO #001-P','petr'),
    (7,timestamp with time zone '2020-01-15 17:34:12 +11:00','PO #002-P','petr'),
    (8,timestamp with time zone '2020-01-05 05:34:12 +11:00','PO #003-P','petr'),
    (9,timestamp with time zone '2020-02-02 15:34:12 +11:00','PO #004-P','petr'),
    (10,timestamp with time zone '2020-01-03 10:34:12 +11:00','PO #005-P','petr');