create table if not exists deliveries
(
    id                integer generated by default as identity
        constraint deliveries_pk
            primary key,
    order_item_id     integer not null
        constraint deliveries_order_items_id_fk
            references order_items,
    delivered_quantity integer not null
);

insert into deliveries (id, order_item_id, delivered_quantity)
values (1, 1, 5),
       (2, 2, 11),
       (3, 3, 12),
       (4, 4, 3),
       (5, 6, 15),
       (6, 7, 8),
       (7, 8, 3),
       (8, 16, 25),
       (9, 17, 26),
       (10, 18, 27),
       (11, 19, 28),
       (12, 20, 29),
       (13, 4, 5),
       (14, 8, 8),
       (15, 8, 6);
